### ISSUE TITLE
Help message if the ymmsl script to be improved

### ISSUE THREAD

**Issue by MireilleSchneider** [DaanVanVugt/ymmsl-dot#2]
Could you please extend the display of the --help option such that it also contains the information that is in the README.md file, i.e. the possible p,s,l options to display more details of the figure?

**Comment by DaanVanVugt** [comment]
You can get this help information with `ymmsl graph --help`. The reason it is not on the main `ymmsl --help` is because we may want to add other commands later. I have updated the docs to include the appropriate command.
